Controllers/CariPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Siniflar;
namespace MVCOnlineTicariOtomasyon.Controllers
{
    
    public class CariPanelController : Controller
    {
        
        // GET: CariPanel
        Context c = new Context();
        
        public ActionResult Index()
        {
            var mail = (string)Session["CariMail"];
            var degerler = c.Carilers.FirstOrDefault(x => x.CariMail == mail);
            ViewBag.m = mail;
            return View(degerler);
        }
        public ActionResult Siparislerim()
        {
            var mail = (string)Session["CariMail"];
            var id = c.Carilers.Where(x => x.CariMail == mail.ToString()).Select(y => y.Cariid).FirstOrDefault();
            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            return View(degerler);
        }
        public ActionResult GelenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var mesajlar = c.Mesajlars.Where(x=> x.Alici ==mail).ToList();
            var gelensayisi = c.Mesajlars.Count(x => x.Alici == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.Mesajlars.Count(x => x.Gonderici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(mesajlar);
        }
        public ActionResult GidenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var mesajlar = c.Mesajlars.Where(x => x.Gonderici == mail).ToList();
            var gidensayisi = c.Mesajlars.Count(x => x.Gonderici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            var gelensayisi = c.Mesajlars.Count(x => x.Alici == mail).ToString();
            ViewBag.d1 = gelensayisi;
            return View(mesajlar);
        }
        public ActionResult MesajDetay(int id)
        {
            var degerler = c.Mesajlars.Count(x => x.MesajID == id).ToString();
            var mail = (string)Session["CariMail"];
            var gidensayisi = c.Mesajlars.Count(x => x.Gonderici == mail).ToString();
            
            ViewBag.d2 = gidensayisi;
            var gelensayisi = c.Mesajlars.Count(x => x.Alici == mail).ToString();
            ViewBag.d1 = gelensayisi;
            return View(degerler);
        }

        //[HttpGet]
        //public ActionResult YeniMesaj()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult YeniMesaj()
        //{
        //    return View();
        //}
    }
}

Views/CariPanel/GelenMesajlar.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<Mesajlar>
@{
    ViewBag.Title = "GelenMesajlar";
    Layout = "~/Views/Shared/CariLayout.cshtml";
}

<h2>Gelen Mesajlar</h2>

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Mailbox</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- icheck bootstrap -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Mesaj Kutusu</h1>

                </div>
            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="row">

            <div class="col-md-3">

                <a href="compose.html" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>

                <div class="card">

                    <div class="card-header">

                        <h3 class="card-title">Klasörler</h3>

                        <div class="card-tools">

                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                        </div>

                    </div>

                    <div class="card-body p-0">

                        <ul class="nav nav-pills flex-column">

                            <li class="nav-item active">

                                <a href="/CariPanel/GelenMesajlar/" class="nav-link">

                                    <i class="fas fa-inbox"></i> Gelen Kutusu

                                    <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="/CariPanel/GidenMesajlar/" class="nav-link">

                                    <i class="far fa-envelope"></i> Gönderdigim Mesajlar

                                    <span class="badge bg-danger float-right">@ViewBag.d1</span>
                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="far fa-file-alt"></i> Taslaklar

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="fas fa-filter"></i> Gereksizler

                                    <span class="badge bg-warning float-right">65</span>

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="far fa-trash-alt"></i> Çöp Kutusu

                                </a>

                            </li>

                        </ul>

                    </div>

                    <!-- /.card-body -->

                </div>

                <!-- /.card -->

                <div class="card">

                    <div class="card-header">

                        <h3 class="card-title">Filtreler</h3>

                        <div class="card-tools">

                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                        </div>

                    </div>

                    <div class="card-body p-0">

                        <ul class="nav nav-pills flex-column">

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="far fa-circle text-danger"></i>

                                    Önemliler

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="far fa-circle text-warning"></i> Promosyonlar

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="#" class="nav-link">

                                    <i class="far fa-circle text-primary"></i>

                                    Sosyal

                                </a>

                            </li>

                        </ul>

                    </div>

                    <!-- /.card-body -->

                </div>

                <!-- /.card -->

            </div>

            <!-- /.col -->

            <div class="col-md-9">

                <div class="card card-primary card-outline">

                    <div class="card-header">

                        <h3 class="card-title">Gelen Kutusu</h3>

                        <div class="card-tools">

                            <div class="input-group input-group-sm">

                                <input type="text" class="form-control" placeholder="Mail Ara">

                                <div class="input-group-append">

                                    <div class="btn btn-primary">

                                        <i class="fas fa-search"></i>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <!-- /.card-tools -->

                    </div>

                    <!-- /.card-header -->

                    <div class="card-body p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                        <div class="table-responsive mailbox-messages">

                            <table class="table table-hover table-striped">

                                <tbody>
                                    @foreach(var x in Model)
                                    {
                                    <tr>

                                        <td>

                                            <div class="icheck-primary">

                                                <input type="checkbox" value="" id="check1">

                                                <label for="check1"></label>

                                            </div>

                                        </td>

                                        <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>

                                        <td class="mailbox-name"><a href="/CariPanel/MesajDetay/@x.MesajID">@x.Gonderici</a></td>

                                        <td class="mailbox-subject">

                                            <b>@x.Konu  </b> - @x.icerik.Substring(0,20).ToString()...

                                        </td>

                                        <td class="mailbox-attachment"></td>

                                        <td class="mailbox-date">@x.Tarih.ToShortDateString()</td>

                                    </tr>
                                    }

                                </tbody>

                            </table>

                            <!-- /.table -->

                        </div>

                        <!-- /.mail-box-messages -->

                    </div>

                    <!-- /.card-body -->

                    <div class="card-footer p-0">

                        <div class="mailbox-controls">

                            <!-- Check all button -->

                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">

                                <i class="far fa-square"></i>

                            </button>

                            <div class="btn-group">

                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>

                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>

                            </div>

                            <!-- /.btn-group -->

                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>

                            <div class="float-right">

                                1-50/200

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>

                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>

                                </div>

                                <!-- /.btn-group -->

                            </div>

                            <!-- /.float-right -->

                        </div>

                    </div>

                </div>

                <!-- /.card -->

            </div>

            <!-- /.col -->

        </div>

        <!-- /.row -->

    </section>


    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- Page Script -->

    <script>
$(function () {

    //Enable check and uncheck all functionality

    $('.checkbox-toggle').click(function () {

      var clicks = $(this).data('clicks')

      if (clicks) {

        //Uncheck all checkboxes

        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)

        $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')

      } else {

        //Check all checkboxes

        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)

        $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')

      }

      $(this).data('clicks', !clicks)

    })



    //Handle starring for glyphicon and font awesome

    $('.mailbox-star').click(function (e) {

      e.preventDefault()

      //detect type

      var $this = $(this).find('a > i')

      var glyph = $this.hasClass('glyphicon')

      var fa    = $this.hasClass('fa')



      //Switch states

      if (glyph) {

        $this.toggleClass('glyphicon-star')

        $this.toggleClass('glyphicon-star-empty')

      }



      if (fa) {

        $this.toggleClass('fa-star')

        $this.toggleClass('fa-star-o')

      }

    })

  })</script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

Views/CariPanel/Index.cshtml
@model MVCOnlineTicariOtomasyon.Models.Siniflar.Cariler
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/CariLayout.cshtml";
}
<br />
<h2>MVC Online Ticari Otomasyon Cari Bilgi Paneli</h2>

@using (Html.BeginForm("Index2", "CariPanel", FormMethod.Post))
{
    <table class="table table-bordered">
        <tr>
            <td><label>Mail Adresi: @HttpContext.Current.User.Identity.Name</label></td>
        </tr>
        <tr>
            <td>@Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td>@Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td>@Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td>@Html.TextBoxFor(x => x.CariSifre, new { @class = "form-control" })</td>
        </tr>

    </table>
    <button class="btn btn-danger">Bilgilerimi Güncelle</button>
}

Views/CariPanel/MesajDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<Mesajlar>
@{
    ViewBag.Title = "MesajDetay";
    Layout = "~/Views/Shared/CariLayout.cshtml";
}


<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Read Mail</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body>

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Mesaj Detayları</h1>

                </div>

            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">


                <div class="col-md-3">

                    <a href="compose.html" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Klasörler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item active">

                                    <a href="/CariPanel/GelenMesajlar/" class="nav-link">

                                        <i class="fas fa-inbox"></i> Gelen Kutusu

                                        <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="/CariPanel/GidenMesajlar/" class="nav-link">

                                        <i class="far fa-envelope"></i> Gönderdigim Mesajlar

                                        <span class="badge bg-danger float-right">@ViewBag.d1</span>
                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-file-alt"></i> Taslaklar

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="fas fa-filter"></i> Gereksizler

                                        <span class="badge bg-warning float-right">65</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-trash-alt"></i> Çöp Kutusu

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Filtreler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-danger"></i>

                                        Önemliler

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-warning"></i> Promosyonlar

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-primary"></i>

                                        Sosyal

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                </div>
                <!-- /.col -->
                @foreach (var x in Model)
                {
                    <div class="col-md-9">

                        <div class="card card-primary card-outline">

                            <div class="card-header">

                                <h3 class="card-title">Mesajı Oku</h3>

                                <div class="card-tools">

                                    <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>

                                    <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>

                                </div>

                            </div>

                            <!-- /.card-header -->

                            <div class="card-body p-0">

                                <div class="mailbox-read-info">

                                    <h5>Konu:</h5>

                                    <h6>

                                        Gönderen: support@adminlte.io

                                        <span class="mailbox-read-time float-right">Tarih</span>

                                    </h6>

                                </div>

                                <!-- /.mailbox-read-info -->

                                <div class="mailbox-controls with-border text-center">

                                    <div class="btn-group">

                                        <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Delete">

                                            <i class="far fa-trash-alt"></i>

                                        </button>

                                        <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Reply">

                                            <i class="fas fa-reply"></i>

                                        </button>

                                        <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Forward">

                                            <i class="fas fa-share"></i>

                                        </button>

                                    </div>

                                    <!-- /.btn-group -->

                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">

                                        <i class="fas fa-print"></i>

                                    </button>

                                </div>

                                <!-- /.mailbox-controls -->

                                <div class="mailbox-read-message">

                                    <p>Hello John,</p>

                                    <p>

                                        Keffiyeh blog actually fashion

                                    </p>

                                    <p>Thanks,<br>Jane</p>

                                </div>

                                <!-- /.mailbox-read-message -->

                            </div>

                            <!-- /.card-body -->
                            <!-- /.card-footer -->

                            <div class="card-footer">

                                <div class="float-right">

                                    <button type="button" class="btn btn-default"><i class="fas fa-reply"></i> Yanıtla</button>

                                    <button type="button" class="btn btn-default"><i class="fas fa-share"></i> İlet</button>

                                </div>

                                <button type="button" class="btn btn-default"><i class="far fa-trash-alt"></i> Sil</button>

                                <button type="button" class="btn btn-default"><i class="fas fa-print"></i> Yazdır</button>

                            </div>

                            <!-- /.card-footer -->

                        </div>

                        <!-- /.card -->

                    </div>
                }
                <!-- /.col -->

            </div>

            <!-- /.row -->

        </div>

    </section>

    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

Views/CariPanel/Siparislerim.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Siparislerim";
    Layout = "~/Views/Shared/CariLayout.cshtml";
}

<h2>Sipariş Geçmişim</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>Ürün Adı</th>
        <th>Fiyat</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Urunlers.UrunlerAd</td>
            <td>@x.Fiyat</td>
            <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
        </tr>
    }
</table>