Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int Departmanid { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepatmanAd { get; set; }
        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }  
    }
}

Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCOnlineTicariOtomasyon.Models.Siniflar;

namespace MVCOnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();

        public ActionResult Index()
        {
            var degerler = c.Departman.Where(x=>x.Durum==true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            d.Durum = true;
            c.Departman.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dep = c.Departman.Find(id);
            dep.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanGetir(int id)
        {
            var dpt = c.Departman.Find(id);
            return View("DepartmanGetir", dpt);
        }
        public ActionResult DepartmanGuncelle(Departman p)
        {
            var dept = c.Departman.Find(p.Departmanid);
            dept.DepatmanAd = p.DepatmanAd;
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult DepartmanDetay(int id)
        {
            var degerler = c.Personels.Where(x => x.Departmanid == id).ToList();
            var dpt = c.Departman.Where(x => x.Departmanid == id).Select(y => y.DepatmanAd).FirstOrDefault();
            ViewBag.d = dpt;
            return View(degerler);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var per = c.Personels.Where(x => x.Personelid == id).Select(y => y.PersonelAd + " " + y.PersonelSoyad).FirstOrDefault();
            ViewBag.dpers = per;
            return View(degerler);
        }
    }
}

Views/Departman/DepartmanDetay.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Detay Sayfası</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Departman Adı: @ViewBag.d</li>
</ol>
<br />
<table class="table table-hover">
    <tr>
        <th>Personel ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        
        <th>Satışlar</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Personelid</td>
            <td>@x.PersonelAd</td>
            <td>@x.PersonelSoyad</td>
            
            <td>
                <a href="/Departman/DepartmanPersonelSatis/@x.Personelid" class="btn btn-default" style="background-color:orangered">Satışlar</a>
            </td>
        </tr>
    }

</table>

Views/Departman/DepartmanEkle.cshtml
@model MVCOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Departman Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.DepatmanAd)
    @Html.TextBoxFor(x => x.DepatmanAd, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

Views/Departman/DepartmanGetir.cshtml
@model MVCOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Güncelleme</h2>

<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.DepatmanAd)
        @Html.TextBoxFor(x => x.DepatmanAd, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Departmanid)

    </div>

    <button class="btn btn-warning">Güncelle</button>
}

Views/Departman/DepartmanPersonelSatis.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Personel Satiş</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı: @ViewBag.dpers</li>
</ol>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th> Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.Satisid</td>
                    <td>@x.Urunlers.UrunlerAd</td>
                    <td>@x.Carilers.CariAd @x.Carilers.CariSoyad</td>
                    <td>@x.Fiyat</td>
                    <td>@x.Adet</td>
                    <td>@x.ToplamTutar</td>
                    <td>@x.Tarih</td>
                    <td><a href="#" class="btn btn-default" style="background-color:royalblue">Yazdır</a></td>
                </tr>
            }
</table>

Views/Departman/Index.cshtml
@using MVCOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-bordered" style="margin-top:20px">
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>
                @k.Departmanid
            </td>
            <td>
                @k.DepatmanAd
            </td>
            <td><a href="/Departman/DepartmanSil/@k.Departmanid" class="btn btn-danger">Sil</a></td>
            <td><a href="/Departman/DepartmanGetir/@k.Departmanid" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Departman/DepartmanDetay/@k.Departmanid" class="btn btn-secondary" 
                   style="background-color:darkblue">Departman Detay</a></td>
        </tr>
    }
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-info">Departman Ekle</a>